version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - atalaya_server_data:/data/
    ports:
      - "8000:8000"

volumes:
  atalaya_server_data: