# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 16:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePinActuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=4095)),
                ('image', models.FileField(upload_to='/code/data/upload/')),
                ('pin_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(27)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
