# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepinactuator',
            name='pin_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(27)]),
        ),
    ]
