# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='pin_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(27)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actuator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
